title: kaliibloggy
description: "a blog project i'll try to keep going"
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed

minima:
  skin: dark

header_pages:
  - about.md
  - inbetween.html
  - friendblogs.md
